10 LET D$ = DATE$()
20 LET T$ = TIME$()
30 IF LEN(D$) = 10 THEN PRINT "OK" ELSE PRINT "BAD"
40 IF MID$(D$, 3, 1) = "-" THEN PRINT "OK" ELSE PRINT "BAD"
50 IF MID$(D$, 6, 1) = "-" THEN PRINT "OK" ELSE PRINT "BAD"
60 IF LEN(T$) = 8 THEN PRINT "OK" ELSE PRINT "BAD"
70 IF MID$(T$, 3, 1) = ":" THEN PRINT "OK" ELSE PRINT "BAD"
80 IF MID$(T$, 6, 1) = ":" THEN PRINT "OK" ELSE PRINT "BAD"
90 END
