10 LET X = 2
20 IF X = 1 THEN PRINT "ONE" ELSEIF X = 2 THEN PRINT "TWO" ELSEIF X = 3 THEN PRINT "THREE" ELSE PRINT "OTHER"
30 LET X = 3
40 IF X = 1 THEN PRINT "ONE" ELSEIF X = 2 THEN PRINT "TWO" ELSEIF X = 3 THEN PRINT "THREE" ELSE PRINT "OTHER"
50 LET X = 9
60 IF X = 1 THEN PRINT "ONE" ELSEIF X = 2 THEN PRINT "TWO" ELSE PRINT "OTHER"
70 END
