10 REM Test logical operators in IF conditions and <> operator
20 REM Test AND in conditions
30 LET X = 7
40 LET Y = 3
50 IF X > 5 AND Y < 10 THEN PRINT "BOTH TRUE"
60 IF X > 10 AND Y < 10 THEN PRINT "WRONG" ELSE PRINT "FIRST FALSE"
70 REM Test OR in conditions
80 IF X = 7 OR Y = 99 THEN PRINT "FIRST TRUE"
90 IF X = 99 OR Y = 3 THEN PRINT "SECOND TRUE"
100 IF X = 99 OR Y = 99 THEN PRINT "WRONG" ELSE PRINT "BOTH FALSE"
110 REM Test NOT in conditions
120 IF NOT (X = 0) THEN PRINT "X NOT ZERO"
130 IF NOT (X = 7) THEN PRINT "WRONG" ELSE PRINT "X IS SEVEN"
140 REM Test XOR in conditions
150 IF X = 7 XOR Y = 3 THEN PRINT "WRONG" ELSE PRINT "BOTH TRUE FOR XOR"
160 IF X = 7 XOR Y = 99 THEN PRINT "ONE TRUE FOR XOR"
170 REM Test <> (not equals) operator
180 IF X <> Y THEN PRINT "X NOT EQUAL Y"
190 IF X <> 7 THEN PRINT "WRONG" ELSE PRINT "X EQUALS 7"
200 LET A$ = "HELLO"
210 LET B$ = "WORLD"
220 IF A$ <> B$ THEN PRINT "STRINGS DIFFERENT"
230 IF A$ <> "HELLO" THEN PRINT "WRONG" ELSE PRINT "STRING MATCH"
240 REM Test compound conditions
250 IF X > 5 AND Y > 2 AND X < 10 THEN PRINT "ALL CONDITIONS TRUE"
260 IF X = 7 OR Y = 7 OR X + Y = 10 THEN PRINT "AT LEAST ONE TRUE"
270 END
