10 PRINT "Testing RND"
20 LET A = RND(-42)
30 LET B = RND
40 LET C = RND(-42)
50 IF A = C THEN PRINT "DETERMINISTIC" ELSE PRINT "NOT DETERMINISTIC"
60 LET D = RND(1)
70 LET E = RND(0)
80 IF D = E THEN PRINT "LAST VALUE WORKS" ELSE PRINT "LAST VALUE BROKEN"
90 END
